### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jules32** [Openscapes/leadership#1]
## Openscapes Roadmap
(moved here from [draft location](https://github.com/MozillaFestival/open-leaders-6/issues/20))

**Project Mission & Summary**

To open up the landscapes of environmental science through open community, data, and code.

We are increasing the value and practice of open data science in environmental science by focusing on three things: engaging researchers, empowering them with existing open tools and communities, and amplifying their successes. We work 1:1 with early career researchers and help them improve their own practices by understanding how they work and identifying their next steps (as a recipe) toward openness. We help them become **champions** to enable other through their lab groups, their teaching, their seminars, and study groups on campus. Openscapes.org focuses has an engaging homepage, empowering resources and “recipes” from the champions, and a blog and twitter handle (@openscapes) to amplify successes (and challenges) and build community.

**What do we need to do?** [TODO, this is is copied from [STEMM](https://github.com/KirstieJane/STEMMRoleModels/issues/1)]
This issue is our roadmap. It's a place to start to investigate the myriad of issues that you can contribute to. Check out the different milestones listed below, but feel free to explore the issues by label too.
Please check out our contribution guidelines and code of conduct to help you get started, and the README for an overview if you haven't read it yet!

**Milestone: create slide decks (engagement)**  
Build off current versions in GoogleSlides, (not starting from scratch) consider switching to xaringan (Rmarkdown)

 - [x] 10 minute version for Oct 17 (NCEAS working group)
 - [x] 45 minute version for Oct 24 (WHOI invited seminar)

**Milestone: create public TED-style pitch (engagement)**

- [x] 5-7 minutes without slides Oct 25 (MozFest)

**Milestone: website mockup**  
May only be in Google doc at this stage. Will ultimately have content for engagement, empowerment, and amplify, but will start with engagement and beginnings of empowerment to launch the site 

- [x] Get feedback at Mozfest (Oct 25-28)

**Milestone: reach out to prospective champions (engagement)**

- [x] Finalize list of cohort 1 champions to work with through 2018 
- [x] Craft and send emails
- [x] Meet in person with 2 new champions (Oct 19-20), formalize engagement questions

**HOW ARE YOU GOING TO ASK PEOPLE TO CONTRIBUTE AND HELP ME - TODO** 

- For the talk: 
- For the website mockup:
- For reaching out to the champions:

**Comment by jules32** [comment]
### Milestones Nov-Dec
In late October the idea solidified of creating the Openscapes Champions program, modeled after Mozilla Open Leaders. 

**Milestone: pilot cohort: intro calls and scheduling**
- [x] engage pilot cohort individually by email
- [x] intro calls with pilot cohort (create slides)
- [x] schedule cohort calls Jan-May (2x/month)
- [x] schedule champion (individual) calls Jan (1x/month)
- [x] engage full cohort (champions' labs) via email

**Milestone: ongoing planning**
- [x] work on Theory of Change with Abdoul
- [x] Open Leaders with Camille
- [x] Discuss Open Leaders architecture, etc, with Abby and Chad

**Milestone: communication**
- [x] publish blog on https://medium.com/@openscapes
- [x] tweet about blog!
- [x] lightning talk at MozFest (5min, no slides)
- [x] lightning talk at Mozilla All Hands (5min, with slides)
- [x] seminar at NCEAS (45 mins)

**Milestone: Website dev**
- [x] website wireframe based on blogdown template
- [x] write copy, work with Kevin
- [x] work with Allison for graphic design
- [x] soft launch December (hopefully!)
- [x] announced launch January

**Upcoming Communications**
- [x] talk at Rotary Club in February
- [x] lightning talk in SF in February
- [x] lightning talk in NYC in February
- [x] academic seminar at UCSB in April
